ad_plugin:
  ad_through_trust_level:
    client: true
    default: 2
    enum: 'TrustLevelSetting'
  ad_through_badge:
    client: true
    default: ''
    type: list

adsense_plugin:
  adsense_publisher_code:
    client: true
    default: ''
  adsense_show_topiclist_top:
    client: true
    default: false
  adsense_ad_slot_topiclist_top:
    client: true
    default: ''
  adsense_ad_slot_topiclist_top_mobile:
    client: true
    default: ''
  adsense_show_topic_top:
    client: true
    default: false
  adsense_ad_slot_topic_top:
    client: true
    default: ''
  adsense_ad_slot_topic_top_mobile:
    client: true
    default: ''
  adsense_show_topic_bottom:
    client: true
    default: false
  adsense_ad_slot_topic_bottom:
    client: true
    default: ''
  adsense_ad_slot_topic_bottom_mobile:
    client: true
    default: ''
  adsense_show_nth_slot_topic:
    client: true
    default: false
  adsense_nth_slot_topic:
    client: true
    default: ''
  adsense_nth_slot_topic_mobile:
    client: true
    default: ''
  adsense_nth_post_code:
    client: true
    default: ''
    min: 1
  adsense_through_trust_level:
    client: true
    default: 2
    enum: 'TrustLevelSetting'
  adsense_through_badge:
    client: true
    default: ''
    type: list
  custom_html_discovery_list_container_top:
    client: true
    default: ''
  custom_html_discovery_list_container_top_mobile:
    client: true
    default: ''
  custom_html_post_bottom:
    client: true
    default: ''
  custom_html_post_bottom_mobile:
    client: true
    default: ''
  custom_html_topic_above_post_stream:
    client: true
    default: ''
  custom_html_topic_above_post_stream_mobile:
    client: true
    default: ''
  custom_html_topic_above_suggested:
    client: true
    default: ''
  custom_html_topic_above_suggested_mobile:
    client: true
    default: ''


revive_plugin:
  revive_publisher_id:
    client: true
    default: ''
  revive_publisher_url:
    client: true
    default: ''
  revive_through_trust_level:
    client: true
    default: 2
    enum: 'TrustLevelSetting'
  revive_topic_list_top_code:
    client: true
    default: ''
    max: 50
  revive_topic_list_top_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 970*250 - billboard
      - 468*60 - banner
      - 320*50 - mobile leaderboard
      - 160*600 - wide skyscraper
      - 234*60 - half banner
      - 125*125 - button
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
      - 300*600 - half page ad
      - 320*100 - large mobile banner
  revive_mobile_topic_list_top_code:
    client: true
    default: ''
    max: 50
  revive_mobile_topic_list_top_ad_sizes:
    client: true
    default: '320*50 - mobile leaderboard'
    type: enum
    choices:
      - 320*50 - mobile leaderboard
      - 300*250 - medium rectangle
      - 336*280 - large rectangle
      - 160*600 - wide skyscraper
      - 234*60 - half banner
      - 125*125 - button
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
      - 300*600 - half page ad
      - 320*100 - large mobile banner
  revive_target_topic_list_top_key_code:
    default: ''
    type: value_list
    client: true
  revive_target_topic_list_top_value_code:
    default: ''
    type: value_list
    client: true
  revive_topic_above_post_stream_code:
    client: true
    default: ''
    max: 50
  revive_topic_above_post_stream_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 970*250 - billboard
      - 468*60 - banner
      - 320*50 - mobile leaderboard
      - 160*600 - wide skyscraper
      - 234*60 - half banner
      - 125*125 - button
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
      - 300*600 - half page ad
      - 320*100 - large mobile banner
  revive_mobile_topic_above_post_stream_code:
    client: true
    default: ''
    max: 50
  revive_mobile_topic_above_post_stream_ad_sizes:
    client: true
    default: '320*50 - mobile leaderboard'
    type: enum
    choices:
      - 320*50 - mobile leaderboard
      - 300*250 - medium rectangle
      - 336*280 - large rectangle
      - 160*600 - wide skyscraper
      - 234*60 - half banner
      - 125*125 - button
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
      - 300*600 - half page ad
      - 320*100 - large mobile banner
  revive_target_topic_above_post_stream_key_code:
    default: ''
    type: value_list
    client: true
  revive_target_topic_above_post_stream_value_code:
    default: ''
    type: value_list
    client: true
  revive_topic_above_suggested_code:
    client: true
    default: ''
    max: 50
  revive_topic_above_suggested_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 970*250 - billboard
      - 468*60 - banner
      - 320*50 - mobile leaderboard
      - 160*600 - wide skyscraper
      - 234*60 - half banner
      - 125*125 - button
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
      - 300*600 - half page ad
      - 320*100 - large mobile banner
  revive_mobile_topic_above_suggested_code:
    client: true
    default: ''
    max: 50
  revive_mobile_topic_above_suggested_ad_sizes:
    client: true
    default: '320*50 - mobile leaderboard'
    type: enum
    choices:
      - 320*50 - mobile leaderboard
      - 300*250 - medium rectangle
      - 336*280 - large rectangle
      - 160*600 - wide skyscraper
      - 234*60 - half banner
      - 125*125 - button
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
      - 300*600 - half page ad
      - 320*100 - large mobile banner
  revive_target_topic_above_suggested_key_code:
    default: ''
    type: value_list
    client: true
  revive_target_topic_above_suggested_value_code:
    default: ''
    type: value_list
    client: true
    max: 50
  revive_nth_post_code:
    client: true
    default: ''
    min: 1
  revive_post_bottom_code:
    client: true
    default: ''
    max: 50
  revive_post_bottom_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 970*250 - billboard
      - 468*60 - banner
      - 320*50 - mobile leaderboard
      - 160*600 - wide skyscraper
      - 234*60 - half banner
      - 125*125 - button
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
      - 300*600 - half page ad
      - 320*100 - large mobile banner
  revive_mobile_post_bottom_code:
    client: true
    default: ''
    max: 50
  revive_mobile_post_bottom_ad_sizes:
    client: true
    default: '320*50 - mobile leaderboard'
    type: enum
    choices:
      - 320*50 - mobile leaderboard
      - 300*250 - medium rectangle
      - 336*280 - large rectangle
      - 160*600 - wide skyscraper
      - 234*60 - half banner
      - 125*125 - button
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
      - 300*600 - half page ad
      - 320*100 - large mobile banner
  revive_target_post_bottom_key_code:
    default: ''
    type: value_list
    client: true
  revive_target_post_bottom_value_code:
    default: ''
    type: value_list
    client: true
