adsense_plugin:
  adsense_publisher_code:
    client: true
    default: ''
  adsense_show_topiclist_top:
    client: true
    default: false
  ad_for_topic_list_top:
    client: 1
    default: 2
    enum: 'AdSelectionSetting'
  adsense_ad_slot_topiclist_top:
    client: true
    default: ''
  adsense_ad_slot_topiclist_top_mobile:
    client: true
    default: ''
  adsense_show_topic_top:
    client: true
    default: false
  adsense_ad_slot_topic_top:
    client: true
    default: ''
  adsense_ad_slot_topic_top_mobile:
    client: true
    default: ''
  adsense_show_topic_bottom:
    client: true
    default: false
  adsense_ad_slot_topic_bottom:
    client: true
    default: ''
  adsense_ad_slot_topic_bottom_mobile:
    client: true
    default: ''
  adsense_show_nth_slot_topic:
    client: true
    default: false
  adsense_nth_slot_topic:
    client: true
    default: ''
  adsense_nth_slot_topic_mobile:
    client: true
    default: ''
  adsense_nth_post_code:
    client: true
    default: ''
    min: 1
  adsense_through_trust_level:
    client: true
    default: 2
    enum: 'TrustLevelSetting'
  adsense_through_badge:
    client: true
    default: ''
    type: list
  custom_html_discovery_list_container_top:
    client: true
    default: ''
  custom_html_discovery_list_container_top_mobile:
    client: true
    default: ''
  custom_html_post_bottom:
    client: true
    default: ''
  custom_html_post_bottom_mobile:
    client: true
    default: ''
  custom_html_topic_above_post_stream:
    client: true
    default: ''
  custom_html_topic_above_post_stream_mobile:
    client: true
    default: ''
  custom_html_topic_above_suggested:
    client: true
    default: ''
  custom_html_topic_above_suggested_mobile:
    client: true
    default: ''
